version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      # Log in to the ECR registry
    - echo Logging in to Amazon ECR...
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  
    -  echo Installing Jib
      # Install Jib
    # -  curl -Lo jib https://github.com/GoogleContainerTools/jib/releases/download/v3.1.0/jib-core-3.1.0.jar
    # -  chmod +x jib
      # Install Docker
      # apt-get update
      # apt-get install -y docker.io
  build:
    commands:
      # Build the Docker image with Jib and push it to ECR
    - mvn compile jib:build -Dimage=$IMAGE_REPO_NAME:$IMAGE_TAG
    - echo Set tag
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
    - echo Push image to ECR
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # docker push <your ECR repository URI>/<image name>:<tag>