name: Deploy to EC2

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: spring-flow
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: demo-0.0.1-SNAPSHOT.jar
          repository: lazur/springboot-cicd
          path: .github/workflows/spring-flow.yml
          # path: /tmp/demo-0.0.1-SNAPSHOT.jar

      - name: Listing directory
        run: ls -la

      - name: Copy re-run script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ./kill-app.sh
          target: /home/ec2-user

      - name: Push to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd staging
            scp -i /tmp/deploy_key demo-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Run script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user
            chmod +x kill-app.sh
            ./kill-app.sh
